### PR TITLE
Add location language pt_BR

### PR DESCRIPTION
**Pull request by walkerfranson**

### CODE REVIEW

**Comment by espellcaste** [comment]
@lesterchan Any change when is this going to be merged?

**Comment by lesterchan** [comment]
send me both the mo/po to my email lesterchan AT gmail, I will commit it to the SVN. I don't include languages in the plugin itself.

**Comment by espellcaste** [comment]
@walkerfranson Can you send it to him? // Você pode enviar essas informações para ele?

Thanks @lesterchan =)

**Comment by walkerfranson** [comment]
I will send @espellcaste 

Thanks @lesterchan

**Comment by espellcaste** [comment]
(y) +1

**Pull request closed without merging**
